#!/usr/bin/env ruby

require 'rubyserial'
require 'colored'

def serial_port
  @serial_port ||= begin
    serial_port_name = Dir['/dev/tty.*'].find { |i| i.include? 'modem' }
    Serial.new serial_port_name
  end
end

@number = []

puts "\nWelcome! Please dial a number.\n".green

loop do
  if @number.any? && (Time.now - @last_digit_read_at) > 2
    if @number.length == 1
      case @number.first
      when 9
        puts '? I\'m going to bed.'.green
        `pmset sleepnow`
      else
        puts ' is an unknown shortcut. :('.red
      end
    else
      puts '? I\'m dialing it for you right now.'.green
      `open "tel://#{@number.join}"`
    end

    puts "\n"
    @number = []
  end

  digit = serial_port.read(1).chomp
  next if digit.empty?

  @number.push digit.to_i
  putc digit

  @last_digit_read_at = Time.now
end
